name = "isshereal-link-shortener"
account_id = "fd2ff8c29a6d58c479032efea6c9ea62"
compatibility_date = "2026-04-01"
main = "src/index.ts"
workers_dev = true

[[kv_namespaces]]
binding = "LINKS_KV"
id = "b37e9bd76fb54edabf6d9c387074931e"

[[kv_namespaces]]
binding = "ANALYTICS_KV"
id = "c06c1a1a7dc04f38ab575bc7008b434e"
